# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_user_phonenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProject',
            fields=[
                ('bid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Default Business Name', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'User List',
                'verbose_name': 'User',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User List'},
        ),
    ]
